### ISSUE TITLE
Couchnode Upsert Response

### ISSUE THREAD

**Issue by jahanzaibaslam-vteams** [IndigoUnited/node-couchnode#1]
Upsert callback function only return err and CAS. I want to get updated or inserted object in response. How can I do this?

**Comment by marcooliveira** [comment]
Upserts always succeed, unless there is a CAS failure or some failure in the server. Both these situations are exposed through the `error` parameter. In terms of getting the updated/inserted object, you already have that, or you wouldn't have been able to `upsert` in the first place.

Can you please elaborate? Not sure if I understood the question, I may be missing something.

**Comment by jahanzaibaslam-vteams** [comment]
Thanks marcooliveira. You fully understood my question and your answer is good enough at least for me. .

**Comment by jahanzaibaslam-vteams** [comment]
Hi! marcooliveira,
I think, I found one more issue in Couchnode. I am unable to get documents if I pass large array of keys to GET method. for example in my case, if I pass  50-60 keys to get  documents. I got error. is there any key limit for get method?

Thanks in advance

**Comment by marcooliveira** [comment]
Hi! That shouldn't be a problem. Can you please provide the call stack and error you're getting?

There is a scenario, if you start hitting the server throughput limit, in which you'll start getting time outs from the server, but that shouldn't be your case, by far. This only happens with tens of thousands of keys (although I wouldn't advise you to get thousands of keys in a single get, as that feels to me like a symptom of some architectural problem).

Closing issue, as this discussion no longer relates to the initial problem, but feel free to open a new issue with your problem.
